version: '3.8'

services:
  # Note: Using Scaleway managed PostgreSQL (no local postgres service needed)

  # API Service
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: b-spot-api
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://USERNAME:PASSWORD@HOST:PORT/DATABASE
      JWT_SECRET: your-secure-jwt-secret-change-this
      PORT: 3000
    ports:
      - "3000:3000"
    # No local postgres dependency - using Scaleway managed DB
    networks:
      - b-spot-network

  # Frontend Service  
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: b-spot-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      VITE_API_BASE_URL: https://api.yourdomain.com
    depends_on:
      - api
    networks:
      - b-spot-network

volumes:
  postgres_data:

networks:
  b-spot-network:
    driver: bridge