name: 'Sync Repository to Public Repo'
description: 'Synchronizes a private repository folder to a public repository'

inputs:
  source-folder:
    description: 'Source folder to sync (e.g., frontend, api)'
    required: true
  public-repo:
    description: 'Public repository name (e.g., Bspot-api/b-spot-frontend)'
    required: true
  sync-token:
    description: 'GitHub token for public repository access'
    required: true
  target-branch:
    description: 'Target branch on public repository (develop or main)'
    required: true
  source-branch:
    description: 'Source branch name for logging'
    required: false
    default: 'feature'

runs:
  using: 'composite'
  steps:
    - name: Sync to Public Repository
      shell: bash
      run: |
        # Git configuration
        git config --global user.name "B-Spot Bot"
        git config --global user.email "bspot.api@gmail.com"
        
        # Clone public repository
        git clone https://x-access-token:${{ inputs.sync-token }}@github.com/${{ inputs.public-repo }}.git temp-sync
        
        # Go to temporary repository
        cd temp-sync
        
        # Checkout target branch
        git checkout ${{ inputs.target-branch }}
        git pull origin ${{ inputs.target-branch }}
        
        # Clean repository (except .git)
        find . -mindepth 1 -not -path './.git*' -delete
        
        # Copy source files (pure copy-paste)
        rsync -av ../${{ inputs.source-folder }}/ . --exclude=.git --exclude=node_modules --exclude=dist
        
        # Commit and push
        if [ -n "$(git status --porcelain)" ]; then
          git add .
          COMMIT_MESSAGE="${{ github.event.pull_request.title || github.event.head_commit.message || github.sha }}"
          git commit -m "$COMMIT_MESSAGE"
          git push origin ${{ inputs.target-branch }}
          echo "✅ ${{ inputs.source-folder }} repository synced successfully to ${{ inputs.target-branch }}"
        else
          echo "ℹ️ No changes detected in ${{ inputs.source-folder }} repository"
        fi
        
        # Cleanup
        cd ..
        rm -rf temp-sync
