name: "✅ Check and Build Projects"

on:
  pull_request:
    branches: [develop, main]

jobs:
  check-and-build-all:
    runs-on: ubuntu-latest
    name: Check and Build All Projects
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # To have complete history
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Check and Build Frontend
        run: |
          cd frontend
          pnpm build
          pnpm lint
      
      - name: Check and Build API
        run: |
          cd api
          pnpm build
          pnpm lint
    
    # This job must pass before merge is allowed
    # Add this job as a required status check in branch protection rules
