name: Sync Frontend to Public Repository

on:
  pull_request_target:
    branches: [develop, main]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  sync-frontend:
    runs-on: ubuntu-latest
    name: Sync Frontend to b-spot-frontend public repo
    
    # This job must pass before merge is allowed
    # Add this job as a required status check in branch protection rules
    
    steps:
      - name: Checkout private repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # To have complete history
      
      - name: Install pnpm
        run: npm install -g pnpm@8
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      
      - name: Install dependencies
        run: |
          # Copy pnpm lock file to frontend folder
          cp pnpm-lock.yaml frontend/
          cd frontend
          pnpm install --frozen-lockfile
      
      - name: Build Frontend (test)
        run: |
          cd frontend
          pnpm build
      
      - name: Sync to Frontend Public Repository
        uses: ./.github/actions/sync-repo
        with:
          source-folder: 'frontend'
          public-repo: 'Bspot-api/b-spot-frontend'
          sync-token: ${{ secrets.FRONTEND_SYNC_TOKEN }}
          target-branch: ${{ github.base_ref }}
          source-branch: ${{ github.head_ref }}
