name: Sync Frontend to Public Repository

on:
  pull_request:
    branches: [develop, main]
  workflow_dispatch: # Allows manual triggering
  workflow_call: # Allows being called by other workflows

jobs:
  sync-frontend:
    runs-on: ubuntu-latest
    name: Sync Frontend to b-spot-frontend public repo
    
    steps:
      - name: Checkout private repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # To have complete history
      
      - name: Install pnpm
        run: npm install -g pnpm@8
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      
      - name: Install dependencies
        run: |
          # Copy pnpm lock file to frontend folder
          cp pnpm-lock.yaml frontend/
          cd frontend
          pnpm install --frozen-lockfile
      
      - name: Build Frontend (test)
        run: |
          cd frontend
          pnpm build
      
      - name: Sync to Frontend Public Repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FRONTEND_SYNC_TOKEN: ${{ secrets.FRONTEND_SYNC_TOKEN }}
        run: |
          # Git configuration
          git config --global user.name "B-Spot Bot"
          git config --global user.email "bspot.api@gmail.com"
          
          # Clone public repository
          git clone https://x-access-token:${FRONTEND_SYNC_TOKEN}@github.com/Bspot-api/b-spot-frontend.git temp-frontend
          
          # Go to temporary repository
          cd temp-frontend
          
          # Get corresponding branch
          BRANCH_NAME="${{ github.ref_name}}"
          if git ls-remote --heads origin $BRANCH_NAME | grep -q $BRANCH_NAME; then
            git checkout $BRANCH_NAME
            git pull origin $BRANCH_NAME
          else
            git checkout -b $BRANCH_NAME
          fi
          
          # Clean repository (except .git)
          find . -mindepth 1 -not -path './.git*' -delete
          
          # Copy frontend files
          rsync -av ../frontend/ . --exclude=.git --exclude=node_modules --exclude=dist
          
          # Copy root configuration files
          cp ../package.json .
          cp ../tsconfig.json .
          cp ../.gitignore .
          
          # Create pnpm-workspace.yaml for single repository
          echo "packages:" > pnpm-workspace.yaml
          echo "  - '.'" >> pnpm-workspace.yaml
          
          # Adapt package.json for single repository
          sed -i 's/"dev": "pnpm --parallel dev"/"dev": "pnpm dev"/' package.json
          sed -i 's/"build": "pnpm --recursive build"/"build": "pnpm build"/' package.json
          sed -i 's/"test": "pnpm --recursive test"/"test": "pnpm test"/' package.json
          sed -i 's/"lint": "pnpm --recursive lint"/"lint": "pnpm lint"/' package.json
          
          # Remove API scripts
          sed -i '/dev:api/d' package.json
          sed -i '/build:api/d' package.json
          sed -i '/start:dev/d' package.json
          
          # Commit and push
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            
            # Get PR title if this is a PR, otherwise use commit message
            COMMIT_MESSAGE="${{ github.sha }}"
            if [ "${{ github.event_name }}" == "pull_request" ]; then
              COMMIT_MESSAGE="${{ github.event.pull_request.title }}"
            elif [ "${{ github.event_name }}" == "push" ] && [ -n "${{ github.event.head_commit.message }}" ]; then
              COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
            fi
            
            git commit -m "$COMMIT_MESSAGE"
            git push origin $BRANCH_NAME
            echo "✅ Frontend repository synced successfully to $BRANCH_NAME"
          else
            echo "ℹ️ No changes detected in Frontend repository"
          fi
      
      - name: Cleanup
        if: always()
        run: |
          rm -rf temp-frontend
